app = 'phone-bills-tc'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 4250
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = 'uploads'
  destination = '/app/uploads'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
